name: Create Tag

on:
  push:
    branches:
      - main
    paths:
      - 'main.go'
      - '.github/workflows/**'
      - 'install.sh'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
          tag_prefix: v
          use_github_release_notes: true
